[build]
  publish = "src/.vuepress/dist"
  command = "yarn build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://nils-kolvenbach.de/*"
  to = "https://nils-kolvenbach.dev/:splat"
  status = 301
  force = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://nils-kolvenbach.netlify.com/*"
  to = "https://nils-kolvenbach.dev/:splat"
  status = 301
  force = true